[project]
name = "MluaScript"
version = "1.0.0"
description = "MaaFramework-driven script controller"
authors = [
    {name = "5656565566", email = "2393963330@qq.com"},
]
dependencies = [
    "maafw>=5.9.2",
    "loguru>=0.7.2",
    "textual>=8.1.1",
    "rich>=13.9.4",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "keyboard>=0.13.5",
    "lupa>=2.4",
    "pillow>=12.1.1",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "pyinstaller>=6.19.0",
    "plyer>=2.1.0",
    "httpx>=0.28.1",
    "playwright>=1.58.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.14.0",
]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
pythonpath = ["src"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--verbose",
    "--strict-markers",
    "--tb=short",
    "--cov=src/mluascript",
#    "--cov-report=html",
    "--cov-report=term-missing",
#    "--cov-fail-under=70",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: unit tests",
]

[project.scripts]
mluascript = "mluascript.__main__:main"

[tool.coverage.run]
omit = [
    "src/mluascript/tui/*",  # 排除整个 tui 目录
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["mluascript*"]
