import { ref } from 'vue'
import { DEFAULT_CUSTOM_COLOR } from './preferences.js'

export function createUiState() {
  return {
    loading: ref(false),
    pendingActionCount: ref(0),
    authChecked: ref(false),
    authenticated: ref(false),
    currentUser: ref(''),
    statusText: ref('准备就绪'),
    activeView: ref('editor'),
    showScreenshot: ref(false),
    showScreenshotFullscreen: ref(false),
    screenshotPosition: ref({ x: 0, y: 64 }),
    imageRecognitionDraft: ref({
      kind: 'ocr',
      imageBase64: '',
       imageMimeType: 'image/png',
       imagePath: '',
       imageWidth: 0,
       imageHeight: 0,
       templatePath: '',
      modelPath: '',
      expected: '',
      targets: '',
      lower: '#000000',
      upper: '#ffffff',
      roiX: null,
      roiY: null,
      roiWidth: null,
      roiHeight: null,
      threshold: 0.8,
      result: null,
      error: '',
    }),
    appTheme: ref('system'),
    colorTheme: ref('classic'),
    customColor: ref(DEFAULT_CUSTOM_COLOR),
    preferencesHydrated: ref(false),
    sidebarCollapsed: ref(false),
    logOrigin: ref('runtime'),
    autoRefresh: ref(true),
    autoSaveFiles: ref(true),
    projectTreeVisible: ref(true),
    projectTreeWidth: ref(240),
    runLogsSelectedDevice: ref('all'),
    runLogsSelectedLevel: ref('all'),
    runLogsAutoScroll: ref(true),
    taskManagerQuery: ref(''),
    taskManagerActiveTab: ref('resource-list'),
    taskManagerResourceQuery: ref(''),
    deviceManagerQuery: ref(''),
    blocklyManagerQuery: ref(''),
    templateEditorModalVisible: ref(false),
    templateEditorModalData: ref(null),
    templateEditorModalCallback: ref(null),
  }
}
